name: Deploy Images to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 2"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: echo "TAG=$(echo $(date +%Y.%m.%d))" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            81aytac/caddy-cloudflare:latest
            81aytac/caddy-cloudflare:${{ env.TAG }}

      - name: Create github release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ env.TAG }}
          allowUpdates: true
          makeLatest: true

# jobs:
#     push-store-image:
#         runs-on: ubuntu-latest
#         steps:
#           - name: 'Checkout GitHub Action'
#             uses: actions/checkout@main

#           - name: 'Login to GitHub Container Registry'
#             uses: docker/login-action@v1
#             with:
#               registry: ghcr.io
#               username: ${{github.actor}}
#               password: ${{secrets.GITHUB_TOKEN}}

#           - name: 'Build caddy-cloudflare Image'
#             run: |
#                 docker build -f ./Dockerfile --tag ghcr.io/spaytac/caddy-cloudflare:latest .
#                 docker push ghcr.io/spaytac/caddy-cloudflare:latest